# Generated by Django 3.1.2 on 2021-01-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ill_history', '0003_auto_20210121_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='unitMeasurement',
        ),
        migrations.AlterField(
            model_name='catalogmeasurement',
            name='unitMeasurement',
            field=models.CharField(max_length=20),
        ),
    ]
