# Generated by Django 3.1.2 on 2021-01-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ill_history', '0004_auto_20210121_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorytest',
            name='nameTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_ill_history.nationcl027'),
        ),
    ]
