# Generated by Django 3.1.7 on 2021-03-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ill_history', '0005_auto_20210121_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comorbidity',
            old_name='IdNameIll',
            new_name='idNameIll',
        ),
        migrations.RenameField(
            model_name='treatmentsession',
            old_name='IdMainIll',
            new_name='idMainIll',
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalogmeasurement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='idSession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comorbidity', to='patient_ill_history.treatmentsession'),
        ),
        migrations.AlterField(
            model_name='electroultrasoundtherapy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electroultrasoundtherapy',
            name='idStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electro_ultrasound_therapy', to='patient_ill_history.stageoftreatment'),
        ),
        migrations.AlterField(
            model_name='eusmedicalstaff',
            name='eus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eus_med_staff', to='patient_ill_history.electroultrasoundtherapy'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='idState',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='patient_ill_history.state'),
        ),
        migrations.AlterField(
            model_name='labmedicalstaff',
            name='laboratoryTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_staff', to='patient_ill_history.laboratorytest'),
        ),
        migrations.AlterField(
            model_name='laboratorytest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laboratorytest',
            name='idState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_test', to='patient_ill_history.state'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='idState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='patient_ill_history.state'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationcl025',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationcl026',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationcl027',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationclpill',
            name='codePill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nationclpill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacotherapy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacotherapy',
            name='idStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacotherapy', to='patient_ill_history.stageoftreatment'),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='idStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapy', to='patient_ill_history.stageoftreatment'),
        ),
        migrations.AlterField(
            model_name='physiotherapymedicalstaff',
            name='physiotherapy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physiotherapy_med_staff', to='patient_ill_history.physiotherapy'),
        ),
        migrations.AlterField(
            model_name='stageoftreatment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stageoftreatment',
            name='idSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_of_treatment', to='patient_ill_history.treatmentsession'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='idStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='patient_ill_history.stageoftreatment'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='idStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='patient_ill_history.stageoftreatment'),
        ),
        migrations.AlterField(
            model_name='surgerymedicalstaff',
            name='surgery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sur_med_staff', to='patient_ill_history.surgery'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='idDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_session', to='patient_ill_history.medicalstaff'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_session', to='patient_ill_history.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='electroultrasoundtherapy',
            unique_together={('nameEus', 'valueEus', 'unitEus', 'dateEus')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('nameImage', 'hostImage', 'dateImage')},
        ),
        migrations.AlterUniqueTogether(
            name='laboratorytest',
            unique_together={('valueTest', 'unitTest', 'dateTest', 'laboratoryName')},
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('valueMeasurement', 'dateMeasurement')},
        ),
        migrations.AlterUniqueTogether(
            name='medicalstaff',
            unique_together={('name', 'surname', 'specialization')},
        ),
        migrations.AlterUniqueTogether(
            name='pharmacotherapy',
            unique_together={('dosePill', 'unitPill', 'datePill')},
        ),
        migrations.AlterUniqueTogether(
            name='physiotherapy',
            unique_together={('namePhysiotherapy', 'valuePhysiotherapy', 'unitPhysiotherapy', 'datePhysiotherapy')},
        ),
        migrations.AlterUniqueTogether(
            name='stageoftreatment',
            unique_together={('stageName', 'startStage', 'endStage')},
        ),
        migrations.AlterUniqueTogether(
            name='surgery',
            unique_together={('DateIntervention',)},
        ),
        migrations.AlterUniqueTogether(
            name='treatmentsession',
            unique_together={('startSession', 'endSession')},
        ),
        migrations.RemoveField(
            model_name='pharmacotherapy',
            name='idMedStaff',
        ),
    ]
